### ISSUE TITLE
updated download link?

### ISSUE THREAD

**Issue by Badcholo** [vdvman1/betterAnvil-forge#17]
will there be a download link for the updated version?
is this the 1.7.10 version?

**Comment by master801** [comment]
There is a download link for the updated version(s), yes it it for Minecraft version 1.7.10 .

http://www.mediafire.com/download/8tegf23us2s5gid/BetterAnvil-3.1.8.jar


Next time please don't make an issue on GitHub, this clutters up actual issues and is redundant as there is already a thread containing all discussions and links for updated versions (excluding 1.8 & 1.8.8).
