### ISSUE TITLE
Crash when crafting anvil

### ISSUE THREAD

**Issue by ZephaniahNoah** [vdvman1/betterAnvil-forge#18]
When I craft an anvil the anvil's ID is -1 and the game crashes once it is crafted.
![anvil](https://s29.postimg.org/uoieqzkp3/2017-08-19_23.26.40.png)
Everything works fine once I uninstalled the mod and I can craft anvils again so i know it's an issue with this mod. I know it's not a conflict because I loaded just this mod in the game and the same problem occurs.
EDIT: The strange thing is that when I test it in eclipse it works. But the built mod glitches like this.

**Comment by master801** [comment]
I need logs

**Comment by ZephaniahNoah** [comment]
I'm using the latest betterAnvil-forge. I compiled it from the source unedited. Here's the crash log:
[crash-2018-02-12_20.04.11-client.txt](https://github.com/user-attachments/files/22130045/crash-2018-02-12_20.04.11-client.txt)

**Comment by master801** [comment]
@ZephaniahNoah Looking into it now

**Comment by master801** [comment]
I think I've ran into this issue before.

It may be due to a old (FML?) bug with substituting items or blocks.

Worst case scenario I'll just whip up a ASM hack to manually replace the block because of the bug.

**Comment by master801** [comment]
@ZephaniahNoah Try the latest build from the master branch

EDIT: You're better off using the dev branch. It has some features that the master branch does not have. It adds an anvil and does not replace Minecraft's anvil and is able to be configured from the Mods gui.

**Comment by ZephaniahNoah** [comment]
Thanks! I can craft anvils now without crashing.
